routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',['uses' => 'Controller@fazerLogin']);
Route::get('/cadastro',['uses' => 'Controller@cadastrar']);

/**
 *      Routes para autenticação do usuário
 * ======================================================
*/

Route::get('/login',['uses' => 'Controller@fazerLogin'])->name('login');
Route::post('/login',['as' => 'user.login' , 'uses' => 'DashboardController@auth']);
Route::get('/dashboard', 'DashboardController@index')->name('dashboard'); //Precisa está assim quando o retorno for return redirect()->route('dashboard');


Route::get('user/moviment' , ['as' => 'moviment.index' , 'uses' => 'MovimentsController@index']);

Route::get('getback'  ,['as' => 'moviment.getback' , 'uses' => 'MovimentsController@getback']);
Route::post('getback' ,['as' => 'moviment.getback.store' , 'uses' => 'MovimentsController@storeGetBack']);


Route::post('group/{group_id}/user' , ['as' => 'group.user.store' , 'uses' => 'GroupsController@userStore']);
Route::get('moviment' , ['as' => 'moviment.application' , 'uses' => 'MovimentsController@application']);

Route::post('moviment' ,['as' => 'moviment.application.store' , 'uses' => 'MovimentsController@storeApplication']);
Route::get('moviment/all' ,['as' => 'moviment.all' , 'uses' => 'MovimentsController@all']);

Route::resource('user' , 'UsersController'); //Define um grupo de rotas
Route::resource('instituition' , 'InstituitionsController' );
Route::resource('group' , 'GroupsController');
Route::resource('instituition.product' , 'ProductsController');


//Route::resource('group/{group_id}/user' , ['as'=> 'group.user.store' , 'uses' => 'GroupsController@index']); 

app/Http/Controllers/InstituitionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Services\InstituitionService;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;
use App\Http\Requests\InstituitionCreateRequest;
use App\Http\Requests\InstituitionUpdateRequest;
use App\Repositories\InstituitionRepository;
use App\Validators\InstituitionValidator;

/**
 * Class InstituitionsController.
 *
 * @package namespace App\Http\Controllers;
 */
class InstituitionsController extends Controller
{
   
    protected $repository;
    protected $validator;
    protected $service;

    public function __construct(InstituitionRepository $repository, InstituitionService $service)
    {
        $this->repository = $repository;
        $this->service  = $service;
    }

    public function index()
    {
        
        $data['instituitions'] = $this->repository->all();
        
        return view('instituitions.index', $data);
    }

   
    public function store(InstituitionCreateRequest $request)
    {
        $request  = $this->service->store($request->all());
        $instituition  = ($request['success'] == true) ? $request['data'] : null;

       
        
        session()->flash('success' , [
            'success' => $request['success'] ,
            'messages'=> $request['messages']
        ]); //Envia a sessão uma única vez para a view
        
        //return redirect()->route('instituition.index');
        return redirect()->route('instituition.index');
    }

    
    public function show($id)
    {
        $data['instituition'] = $this->repository->find($id);
        
        return view('instituitions.show' , $data);
        
    }

    
    public function edit($id)
    {
        $data['instituition'] = $this->repository->find($id);

        return view('instituitions.edit', $data);
    }


    public function update(Request $request, $id)
    {
        $request  = $this->service->update($request->all() , $id);
        $instituition  = ($request['success'] == true) ? $request['data'] : null;
       
        
        session()->flash('success' , [
            'success' => $request['success'] ,
            'messages'=> $request['messages']
        ]); //Envia a sessão uma única vez para a view
        
        //return redirect()->route('instituition.index');
        return redirect()->route('instituition.index');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleted = $this->repository->delete($id);

        if (request()->wantsJson()) {

            return response()->json([
                'message' => 'Instituition deleted.',
                'deleted' => $deleted,
            ]);
        }

        return redirect()->back()->with('message', 'Instituition deleted.');
    }
}

resources/views/instituitions/edit.blade.php
@extends('templates.master')

@section('conteudo-view')
    @if(session('success'))
        <h3>{{ session('success')['messages'] }}</h3>
    @endif

    {!! Form::model( $instituition , ['route' => ['instituition.update' , $instituition->id] , 'method' => 'put' , 'class' => 'form-padrao']) !!} 
    @include('templates.formulario.input' , [ 'Nome' => 'Instituição' , 'input' => 'name' , 'attributes' => ['placeholder' => 'Nome' , 'autocomplete' => 'off']])

    @include('templates.formulario.submit', ['input' => 'Atualizar'])
    {!! Form::close() !!}
@endsection

resources/views/instituitions/index.blade.php
@extends('templates.master')

@section('conteudo-view')

@if(session('success'))
    <h3>{{ session('success')['messages'] }}</h3>
@endif

{!! Form::open(['route' => 'instituition.store' , 'method' => 'POST' , 'class' => 'form-padrao']) !!} 
@include('templates.formulario.input' , [ 'label' => 'Instituição' , 'input' => 'name' , 'attributes' => ['placeholder' => 'Nome' , 'autocomplete' => 'off']])

@include('templates.formulario.submit', ['input' => 'Cadastrar'])
{!! Form::close() !!}
<!--Listagem de instituiçoes-->
<table class="default-table">
     <thead>
       <tr>
         <td>#</td>
         <td>Nome da Instituição</td>
         <td>Opções</td>
       </tr>
     </thead>

     <tbody>
       @foreach($instituitions as $inst)
       <tr>
         <td>{{ $inst->id }}</td>
         <td>{{ $inst->name }}</td>
         <td>{!! Form::open(['route' => ['instituition.destroy' , $inst->id] , 'method' => 'DELETE' ]) !!}
              {!!Form::submit('Remover') !!}
              {!! Form::close() !!}
            
              <a href="{{ route('instituition.show' , $inst->id )}}">Detalhes</a>
              <a href="{{ route('instituition.edit' , $inst->id )}}">Editar</a>
              <a href="{{ route('instituition.product.index' , $inst->id)}}" >Produtos</a>

         </td>
       </tr>
       @endforeach


     </tbody>
  </table>



@endsection

resources/views/instituitions/show.blade.php
@extends('templates.master')

@section('conteudo-view')

<header> 
    <h1>{{ $instituition->name }}</h1>
</header>

<!-- Tabela de listagem dinâmica -->
@include('group.list' , ['var' => $instituition->groups])

@endsection