routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',['uses' => 'Controller@fazerLogin']);
Route::get('/cadastro',['uses' => 'Controller@cadastrar']);

/**
 *      Routes para autenticação do usuário
 * ======================================================
*/

Route::get('/login',['uses' => 'Controller@fazerLogin'])->name('login');
Route::post('/login',['as' => 'user.login' , 'uses' => 'DashboardController@auth']);
Route::get('/dashboard', 'DashboardController@index')->name('dashboard'); //Precisa está assim quando o retorno for return redirect()->route('dashboard');


Route::get('user/moviment' , ['as' => 'moviment.index' , 'uses' => 'MovimentsController@index']);

Route::get('getback'  ,['as' => 'moviment.getback' , 'uses' => 'MovimentsController@getback']);
Route::post('getback' ,['as' => 'moviment.getback.store' , 'uses' => 'MovimentsController@storeGetBack']);


Route::post('group/{group_id}/user' , ['as' => 'group.user.store' , 'uses' => 'GroupsController@userStore']);
Route::get('moviment' , ['as' => 'moviment.application' , 'uses' => 'MovimentsController@application']);

Route::post('moviment' ,['as' => 'moviment.application.store' , 'uses' => 'MovimentsController@storeApplication']);
Route::get('moviment/all' ,['as' => 'moviment.all' , 'uses' => 'MovimentsController@all']);

Route::resource('user' , 'UsersController'); //Define um grupo de rotas
Route::resource('instituition' , 'InstituitionsController' );
Route::resource('group' , 'GroupsController');
Route::resource('instituition.product' , 'ProductsController');


//Route::resource('group/{group_id}/user' , ['as'=> 'group.user.store' , 'uses' => 'GroupsController@index']); 

resources/views/templates/master.blade.php
<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<meta charset="utf-8">
		<title>Sistema de controle de Investimento</title>
		@yield('css-view')
		<link rel="stylesheet" href="{{asset('css/stylesheet.css')}}">
		<link href="https://fonts.googleapis.com/css?family=Fredoka+One" rel="stylesheet">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	</head>
	<body>
		
		@include('templates.menu-lateral')
		  <section id="view-conteudo">
			@yield('conteudo-view')
		  </section>

		@yield('js-view')
		
	</body>
</html>

resources/views/templates/menu-lateral.blade.php
<nav id="principal">

	<ul>
		<li>
			<a href="">
				<i ></i>
				<h3 style="margin-left: -50px;color: yellow;">InvestidorLegal</h3>
			</a>
		</li>
	</ul>

	<ul>
		<li>
			<a href="{{ route('user.index')}}">
				<i class="fa fa-address-book"  aria-hidden="true"></i>
				<h3>Usuários</h3>
			</a>
		</li>
	</ul>
	

	<ul>
		<li>
			<a href="{{ route('instituition.index') }}">
				<i class="fa fa-building" aria-hidden="true"></i>
				<h3>Instituições</h3>
			</a>
		</li>
	</ul>
	
	<ul>
		<li>
			<a href="{{ route('group.index') }}">
				<i class="fa fa-users" aria-hidden="true"></i>
				<h3>Grupos</h3>
			</a>
		</li>
	</ul>


	<ul>
		<li>
			<a href="{{ route('moviment.application') }}">
				<i class="fa fa-money" aria-hidden="true"></i>
				<h3>Investir</h3>
			</a>
		</li>
	</ul>

	<ul>
		<li>
			<a href="{{ route('moviment.getback') }}">
				<i class="fa fa-share" aria-hidden="true"></i>
				<h3>Resgatar</h3>
			</a>
		</li>
	</ul>


	<ul>
		<li>
			<a href="{{ route('moviment.index') }}">
				<i class="fa fa-dollar" aria-hidden="true"></i>
				<h3>Aplicações</h3>
			</a>
		</li>
	</ul>

	<ul>
		<li>
			<a href="{{ route('moviment.all') }}">
				<i class="fa fa-exchange" aria-hidden="true"></i>
				<h3>Extrato</h3>
			</a>
		</li>
	</ul>

</nav>